#!/usr/bin/env python3
# Copyright 2015 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""A small utility to extract locale information from region database."""

import json
import sys


# The region database install by virtual/chromeos-regions.
CROS_REGION_DATABASE = "/usr/share/misc/cros-regions.json"


def main():
    db_path = sys.argv[1] if len(sys.argv) > 1 else CROS_REGION_DATABASE

    with open(db_path, "rb") as f:
        db = json.load(f)

    # In recovery image we can't afford to put JSON programs so we want to
    # provide a simple database.
    for key, value in db.items():
        print("%s\t%s" % (key, value["locales"][0]))


if __name__ == "__main__":
    main()
